name = "PolaronDoubleTimePIMC"
uuid = "ae024362-f885-449c-9b77-5bc69ce4c2d6"
authors = ["Jarvist Moore Frost"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
